const BLOCKSCOUT="https://robinhoodchain.blockscout.com",OPEN_SEA="https://opensea.io",OPEN_SEA_API="https://api.opensea.io/api/v2",CHAIN="robinhood";
function response(statusCode,body){return{statusCode,headers:{"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=300, stale-while-revalidate=600","access-control-allow-origin":"same-origin","access-control-allow-methods":"GET, OPTIONS","access-control-allow-headers":"content-type"},body:JSON.stringify(body)}}
const validAddress=v=>typeof v==="string"&&/^0x[a-fA-F0-9]{40}$/.test(v),cleanName=v=>String(v||"").replace(/\s+/g," ").trim().slice(0,160);
function safeExternalUrl(v){if(typeof v!=="string"||!v.trim())return null;try{const u=new URL(v.trim(),BLOCKSCOUT);if(!/^https?:$/.test(u.protocol)||u.hostname.toLowerCase()==="robinhoodchain.blockscout.com")return null;return u.href}catch{return null}}
function marketplaceHost(h){h=String(h||"").toLowerCase();return["opensea.io","magiceden.io","blur.io","tensor.trade","rarible.com","looksrare.org","zora.co","reservoir.market","nftx.io","element.market","okx.com","foundation.app"].some(x=>h===x||h.endsWith(`.${x}`))}
function marketplaceLabel(url){try{const h=new URL(url).hostname.toLowerCase();if(h.includes("opensea"))return"OpenSea";if(h.includes("magiceden"))return"Magic Eden";if(h.includes("tensor"))return"Tensor";if(h.includes("blur"))return"Blur";if(h.includes("rarible"))return"Rarible";if(h.includes("looksrare"))return"LooksRare";if(h.includes("zora"))return"Zora";return"Marketplace"}catch{return"Marketplace"}}
function extractUrls(text){const out=new Set,s=String(text||"").replace(/\\u002F/gi,"/").replace(/\\u003A/gi,":").replace(/\\u0026/gi,"&").replace(/\\\//g,"/").replace(/&amp;/gi,"&");for(const re of [/https?:\/\/[^\s"'<>\\]+/gi,/(?:href|url|external_app_url|external_url)\s*[:=]\s*["']([^"']+)["']/gi]){let m;while((m=re.exec(s))){const u=safeExternalUrl(m[1]||m[0]);if(u)out.add(u)}}return[...out]}
function marketplaceCandidatesFromHtml(html){const source=String(html||""),urls=extractUrls(source),out=[];const marker=/marketplaces?/i.exec(source);if(marker){for(const url of extractUrls(source.slice(Math.max(0,marker.index-4000),marker.index+12000))){try{if(marketplaceHost(new URL(url).hostname))out.push({url,label:marketplaceLabel(url),source:"blockscout-token-marketplaces"})}catch{}}}for(const url of urls){try{if(marketplaceHost(new URL(url).hostname))out.push({url,label:marketplaceLabel(url),source:"blockscout-token-page"})}catch{}}const seen=new Map;for(const x of out)seen.set(x.url,x);return[...seen.values()]}
async function fetchText(url,timeout=8000){const c=new AbortController,t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{accept:"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 RHC-Mint-Radar/1.0"},redirect:"follow",signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function fetchJson(url,headers={},timeout=6500){const c=new AbortController,t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{accept:"application/json",...headers},signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function metadataMarketplace(v){const out=[];const walk=x=>{if(!x||typeof x!=="object")return;if(Array.isArray(x)){x.forEach(walk);return}for(const[k,val]of Object.entries(x)){if(typeof val==="string"){const u=safeExternalUrl(val);if(u)try{if(marketplaceHost(new URL(u).hostname))out.push({url:u,label:marketplaceLabel(u),source:`blockscout-metadata:${k}`})}catch{}}else walk(val)}};walk(v);return out}
function configuredRobinhoodMarketplace(address){return validAddress(address)?{url:`${OPEN_SEA}/token/robinhood/${address}`,label:"OpenSea",source:"blockscout-marketplace-config",tokenPage:`${BLOCKSCOUT}/token/${address}`}:null}
async function resolveFromBlockscout(address){if(!validAddress(address))return null;const tokenPage=`${BLOCKSCOUT}/token/${address}`;try{const html=await fetchText(tokenPage),c=marketplaceCandidatesFromHtml(html);if(c[0])return{...c[0],tokenPage}}catch{}try{const token=await fetchJson(`${BLOCKSCOUT}/api/v2/tokens/${address}`).catch(()=>null),instances=await fetchJson(`${BLOCKSCOUT}/api/v2/tokens/${address}/instances?limit=8`).catch(()=>null),c=[];for(const item of instances?.items||[]){for(const v of[item?.external_app_url,item?.metadata?.external_app_url,item?.metadata?.external_url]){const u=safeExternalUrl(v);if(u)try{if(marketplaceHost(new URL(u).hostname))c.push({url:u,label:marketplaceLabel(u),source:"blockscout-token-instance",tokenPage})}catch{}}c.push(...metadataMarketplace(item?.metadata).map(x=>({...x,tokenPage})))}c.push(...metadataMarketplace(token?.metadata).map(x=>({...x,tokenPage})));if(c[0])return c[0]}catch{}return null}
function slugify(v){return cleanName(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[’'`]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-{2,}/g,"-").toLowerCase()}
function scoreName(a,b){a=slugify(a);b=slugify(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .85;return a.replace(/-/g,"")===b.replace(/-/g,"")?0.8:0}
function extractCollections(payload){const out=[];const walk=v=>{if(!v||typeof v!=="object")return;if(Array.isArray(v)){v.forEach(walk);return}const slug=v.collection||v.slug,name=v.name||v.collection_name||v.collectionName;if(typeof slug==="string")out.push({slug,name:name||"",url:`${OPEN_SEA}/collection/${encodeURIComponent(slug)}`});if(typeof v.opensea_url==="string")out.push({slug:null,name:name||"",url:v.opensea_url});Object.values(v).forEach(walk)};walk(payload);return out}
async function resolveWithOpenSeaApi(address,name,key){const headers={"x-api-key":key};if(validAddress(address))try{const x=await fetchJson(`${OPEN_SEA_API}/chain/${CHAIN}/contract/${address}`,headers),c=extractCollections(x).map(v=>({...v,score:scoreName(v.name,name)})).sort((a,b)=>b.score-a.score);if(c[0]?.url&&c[0].score>=.8)return{...c[0],label:"OpenSea",source:"opensea-contract"}}catch{}if(name)try{const x=await fetchJson(`${OPEN_SEA_API}/search?query=${encodeURIComponent(name)}&asset_types=collection&limit=20`,headers),c=extractCollections(x).map(v=>({...v,score:scoreName(v.name,name)})).filter(v=>v.score>=.8).sort((a,b)=>b.score-a.score);if(c[0])return{...c[0],label:"OpenSea",source:"opensea-search"}}catch{}return null}
exports.handler=async event=>{if(event.httpMethod==="OPTIONS")return response(204,{});if(event.httpMethod!=="GET")return response(405,{error:"GET only",code:"METHOD_NOT_ALLOWED"});const p=event.queryStringParameters||{},address=String(p.address||"").trim(),name=cleanName(p.name);if(address&&!validAddress(address))return response(400,{error:"invalid address",code:"INVALID_ADDRESS"});if(!address&&!name)return response(400,{error:"address or name required",code:"MISSING_QUERY"});if(address){const x=await resolveFromBlockscout(address);if(x)return response(200,{found:true,url:x.url,label:x.label,source:x.source,tokenPage:x.tokenPage,flow:["contract","blockscout-token-page","marketplaces"]})}const key=process.env.OPENSEA_API_KEY||"";if(key){const x=await resolveWithOpenSeaApi(address,name,key);if(x)return response(200,{found:true,url:x.url,label:x.label,source:x.source,flow:["contract","opensea-api","collection"]})}if(address){const x=configuredRobinhoodMarketplace(address);return response(200,{found:true,url:x.url,label:x.label,source:x.source,tokenPage:x.tokenPage,flow:["contract","blockscout-token-page","marketplaces","opensea-configured-link"]})}return response(404,{found:false,code:"MARKETPLACE_NOT_FOUND"})};
